default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password

development:
  primary: &primary_development
    <<: *default
    database: a_development

  cache:
    <<: *primary_development
    database: a_development_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_development
    database: a_development_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_development
    database: a_development_cable
    migrations_paths: db/cable_migrate
